# Generated by Django 4.2.23 on 2025-08-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_calendarevent_maplocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
